export const Posters = {
  1917: '/iZf0KyrE25z1sage4SYFLCCrMi9.jpg',
  Joker: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
  'Rick and Morty': '/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg',
  'Black Mirror': '/pXeuSWSKgWUnhRFHZ4TjAUU8lbE.jpg',
  'Jojo Rabbit': '/7GsM4mtM0worCtIVeiQt28HieeN.jpg',
  Parasite: '/6EM7Jm3veKSW9ELMajSSxslYWDa.jpg',
  Passengers: '/8NT7Tnq9s0Z4CRbz3WQR15wHCiQ.jpg',
  'Shawshank Redemption': '/5KCVkau1HEl7ZzfPsKAPM0sMiKc.jpg',
  'The godfather': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'Frozen 2': '/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg',
  'Baby Driver': '/dN9LbVNNZFITwfaRjl4tmwGWkRg.jpg',
  'Titanic (1997)': '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
  'Star Wars': '/db32LaOibwEliAmSL2jjDF6oDdj.jpg',
  'Kingsman: The Secret Service': '/ay7xwXn1G9fzX9TUBlkGA584rGi.jpg',
  'The Social Network': '/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
  'Good Will Hunting': '/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg',
  'Ralph breaks the internet': '/qEnH5meR381iMpmCumAIMswcQw2.jpg',
  It: '/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg',
};
